# Generated by Django 5.0.6 on 2024-06-06 17:01

import netscan360.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan360', '0002_scan_hosts_discovered_scan_os_version_scan_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[netscan360.validators.validate_ip]),
        ),
    ]
